### PR TITLE
Adding aggregate level to dataset if not included

### PR DESCRIPTION
**Pull request by ghop02**
This will fix the breakage in the data update by making sure that all data has an aggregate level.

### CODE REVIEW

**Review by TomGoBravo — COMMENTED** [review]
What is the breakage that this fixes? I don't see anything in the notification channels or recent suspicious commits in the git log.

**Comment by ghop02** [comment]
> What is the breakage that this fixes? I don't see anything in the notification channels or recent suspicious commits in the git log.

This fixes: https://github.com/covid-projections/covid-data-model/actions/workflows/update_repo_datasets.yml

Also, it would fix any `get_subset` queries on datasets that don't have aggregate level

**Review by TomGoBravo — APPROVED** [review]
This'll do for now. It'd be nice to have better test coverage and some way to have subset query by level work for datasets not created via fips-related methods like from_fips_timeseries_df

**Comment by ghop02** [comment]
> This'll do for now. It'd be nice to have better test coverage and some way to have subset query by level work for datasets not created via fips-related methods like from_fips_timeseries_df

Thanks, yup definitely agree!

**Pull request merged**
