### PR TITLE
drop dates without real values in the timeseries

### PR DESCRIPTION
**Pull request by TomGoBravo**
Tested by running `python ./run.py data filter-drop-na-dates data/multiregion.csv data/multiregion-drop-na-dates.csv` and looking at `vimdiff data/multiregion.csv data/multiregion-drop-na-dates.csv`. File size dropped from 84MB to 74MB; I was hoping for a bigger drop but code is written now.

### CODE REVIEW

**Review by ghop02 — COMMENTED** [review]
I like this overall! I'm wondering, will this affect the daily new cases average in the metrics? We frontfill the columns with 0s, so when the first case hits, it's averaging over 6 zeros and 1 value.  If this change causes those front padded zeroes to go away, it might change the calculation.  

One way we could fix this is to make sure that we start the series at a given date in the top level metrics code, but open to suggestions.

It definitely feels too fragile now that this change would ultimately affect the metric calculations

**Comment by TomGoBravo** [comment]
> I like this overall! I'm wondering, will this affect the daily new cases average in the metrics? We frontfill the columns with 0s, so when the first case hits, it's averaging over 6 zeros and 1 value. If this change causes those front padded zeroes to go away, it might change the calculation.
> 
> One way we could fix this is to make sure that we start the series at a given date in the top level metrics code, but open to suggestions.
> 
> It definitely feels too fragile now that this change would ultimately affect the metric calculations

Is there are easy way to check how this PR changes the daily new cases output?

**Comment by ghop02** [comment]
> > I like this overall! I'm wondering, will this affect the daily new cases average in the metrics? We frontfill the columns with 0s, so when the first case hits, it's averaging over 6 zeros and 1 value. If this change causes those front padded zeroes to go away, it might change the calculation.
> > One way we could fix this is to make sure that we start the series at a given date in the top level metrics code, but open to suggestions.
> > It definitely feels too fragile now that this change would ultimately affect the metric calculations
> 
> Is there are easy way to check how this PR changes the daily new cases output?

The easiest would be to simply run a build on the branch (with the data updated).  The slightly more involved would just be to run the api for a couple places and look at the differentces

**Comment by TomGoBravo** [comment]
No longer relevant. We changed to wide dates, which is waaaay smaller.

**Pull request closed without merging**
