### PR TITLE
Reorganize repo add tests

### PR DESCRIPTION
**Pull request by ghop02**
Hi! No need to accept these changes, but wanted to provide a structure that I've found useful in other projects in case it's helpful (based loosely off of the [Stripe Python](https://github.com/stripe/stripe-python) project).

I wanted to hook the tests to github actions, but wanted to throw this up first.

Just moves most of the python code into its own package (to make it a bit easier to test), also runs the `black` code formatter to run some standard python formatting. 

Feel free to disregard, just wanted to contribute in some way!

### CODE REVIEW

**Comment by jredding** [comment]
Oh this is really awesome - thank you for poking your head in and getting the testing infrastructure bootstrapped. 

Last night the team moved over to Jupyter notebook porting over the existing run.py to the new notebook. Could we use the same framework for testing those notebooks?

**Comment by ghop02** [comment]
Great! The new structure on master does look good!

When you mention testing those notebooks, what sorts of testing do you have in mind? 

In projects where we've worked with jupyter notebooks in the past, I've always tried to keep any real "business logic" out of the notebooks so it's easier to test (which it looks like y'all are moving to as well!). Using them for more than just trying out different simulations or parameters tends more towards chaos.

**Comment by ghop02** [comment]
Oh also! what version of python are you using? If you use 3.7, you can take advantage of Data Classes which I think would be hugely helpful for organization (reduces the number of `dicts` you're passing around)

**Comment by ghop02** [comment]
Added in a github action that runs the tests as well - looks like that's passing in my repo

**Comment by davidstrauss** [comment]
Let's ensure we can land these changes sometime today. When would you like to do one last re-roll so we can merge this for good? Do you need any help re-rolling?

**Comment by ghop02** [comment]
Sounds good! By re-rolling do you mean merging in the changes for master? If it's just the changes that are in master now, I can take a look in a couple hours!

If you want to merge in your branch first, that's fine too - don't think they should be too difficult to add on.

**Comment by crwilcox** [comment]
Thanks @ghop02 !

This is an awesome improvement. Only had one question from looking at this. Is there a reason you chose a makefile over tox/nox? It is a discussion that can be had later as well but it seemed unique to most python projects I work in. 

Also, to be clear, I don't think it is worth focusing on now and would rather see this merged.

**Comment by ghop02** [comment]
@crwilcox there was not, it was more of a quick hack to get things working. 

My tox experience is limited, so when I've used it in other projects, it's usually copying from another open source project.  But definitely down (after I finish this up) to improve the setup/test runner!

**Comment by ghop02** [comment]
@davidstrauss @crwilcox updated to master.

[this commit](https://github.com/covid-projections/covid-data-model/commit/47aff281b53f55e4e6efb34e6b4d652e9d8fd407) wasn't necessary because of a logic change in how the data was loaded.

I believe it should be good to go! (at least for now).

I added some comments in #7 around what this _doesn't_ address, would love to hear your feedback!

**Comment by davidstrauss** [comment]
I have some good news and bad news. Merging JHU probably needs to happen first, but can we get this in right after?

**Comment by ghop02** [comment]
Haha no problem! (not sure what JHU is) but if there's more merge conflicts to resolve, should be fine (the advantages of a younger codebase!)

**Comment by davidstrauss** [comment]
Can we also break this up into a series of PRs as part of the post-JHU reroll?

**Comment by davidstrauss** [comment]
@ghop02 Are you on our Slack instance? @mikelehen would like to discuss some of the planned changes.

**Comment by ghop02** [comment]
@davidstrauss I don't know much about what the JHU reroll involves - is there an open branch?

Multiple PRs is totally fine! If you want to cut over to this structure, getting it in earlier rather than later seems easier?

Not being officially involved, I definitely defer to anyone on the team on the steps to take there!

**Comment by mikelehen** [comment]
@ghop02 Hey, yeah. I'm just nervous about reviewing this as-is, since it has file renames, moving code, reformatting, etc. all mixed together.  In isolation, these are each 100% safe, but when combined, it makes it impossible to review (git doesn't even recognize some of the file renames as renames anymore), and if there's any manual intervention (manual merging of conflicts, etc.) I worry that we could make a mistake.

So breaking this into small-ish isolated PRs that only do a single thing would be great.  If you need more guidance, let me know.

The JHU work is an effort to add John Hopkins University data as an available dataset.  It lives in https://github.com/covid-projections/covid-data-model/tree/notebook_refactor right now.  This is blocking a couple efforts on our end, so we're trying to get it merged sooner-than-later and don't want to risk having to deal with merge conflicts, etc.

Thanks/sorry!  We definitely appreciate the work.

**Comment by ghop02** [comment]
@mikelehen @davidstrauss sounds good!

With each new merge it definitely becomes more brittle - the initial PR was created when there was only a `run.py` file.

I'm going to close this PR and will move discussion of how to break up the PRs in the ticket.

Thanks for the direction!

**Pull request closed without merging**
